=== timhoelsken/easygoingcalculatorwithoutnumbers/Normalisation/resources/normalisation.dtd
<!ELEMENT Normalisation (Relation, FunctionalDependency+)>

<!ELEMENT Relation (Column+)>
<!ELEMENT Column (#PCDATA)>

<!ELEMENT FunctionalDependency (FunctionallyDependentOn+, FunctionallyAffected+)>
<!ELEMENT FunctionallyDependentOn (#PCDATA)>
<!ELEMENT FunctionallyAffected (#PCDATA)>

<!ATTLIST Relation
	name CDATA #REQUIRED>

=== timhoelsken/easygoingcalculatorwithoutnumbers/Normalisation/resources/MITARBEITER.xml
<?xml version="1.0"?>

<!DOCTYPE Normalisation SYSTEM "normalisation.dtd">

<Normalisation>
	<RelationSchema name="MITARBEITER">
		<Column>PERSONALNUMMER</Column>
		<Column>NAME</Column>
		<Column>VORNAME</Column>
		<Column>ABTEILUNG</Column>
		<Column>GEBÄUDE</Column>
		<Column>POSITION</Column>
		<Column>GEHALT</Column>
		<Column>ADRESSE</Column>
		<Column>ANZAHL_MITARBEITER</Column>
		<Column>FACHGEBIET</Column>
		<Column>FAHRZEUG</Column>
		<Column>PARKPLATZ</Column>
		<Column>BODENBELAG</Column>
	</RelationSchema>
    <FunctionalDependency>
        <FunctionallyDependentOn>PERSONALNUMMER</FunctionallyDependentOn>
        <FunctionallyAffected>NAME</FunctionallyAffected>
        <FunctionallyAffected>VORNAME</FunctionallyAffected>
    </FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>PERSONALNUMMER</FunctionallyDependentOn>
		<FunctionallyDependentOn>POSITION</FunctionallyDependentOn>
		<FunctionallyAffected>ABTEILUNG</FunctionallyAffected>
		<FunctionallyAffected>FAHRZEUG</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
	   <FunctionallyDependentOn>POSITION</FunctionallyDependentOn>
        <FunctionallyAffected>GEHALT</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>ABTEILUNG</FunctionallyDependentOn>
		<FunctionallyAffected>GEBÄUDE</FunctionallyAffected>
		<FunctionallyAffected>ANZAHL_MITARBEITER</FunctionallyAffected>
		<FunctionallyAffected>FACHGEBIET</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
        <FunctionallyDependentOn>GEBÄUDE</FunctionallyDependentOn>
        <FunctionallyAffected>ADRESSE</FunctionallyAffected>
    </FunctionalDependency>
	<FunctionalDependency>
        <FunctionallyDependentOn>FAHRZEUG</FunctionallyDependentOn>
        <FunctionallyAffected>PARKPLATZ</FunctionallyAffected>
    </FunctionalDependency>
    <FunctionalDependency>
        <FunctionallyDependentOn>PARKPLATZ</FunctionallyDependentOn>
        <FunctionallyAffected>GEBÄUDE</FunctionallyAffected>
        <FunctionallyAffected>BODENBELAG</FunctionallyAffected>
    </FunctionalDependency>
</Normalisation>

=== timhoelsken/easygoingcalculatorwithoutnumbers/Normalisation/resources/F2.xml
<?xml version="1.0"?>

<!DOCTYPE Normalisation SYSTEM "normalisation.dtd">

<Normalisation>
	<RelationSchema name="F(2)">
		<Column>A</Column>
		<Column>B</Column>
		<Column>C</Column>
	</RelationSchema>
	<FunctionalDependency>
		<FunctionallyDependentOn>A</FunctionallyDependentOn>
		<FunctionallyAffected>B</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>B</FunctionallyDependentOn>
		<FunctionallyAffected>C</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>A</FunctionallyDependentOn>
		<FunctionallyDependentOn>B</FunctionallyDependentOn>
		<FunctionallyAffected>C</FunctionallyAffected>
	</FunctionalDependency>
</Normalisation>

=== timhoelsken/easygoingcalculatorwithoutnumbers/Normalisation/resources/LIEFER.xml
<?xml version="1.0"?>

<!DOCTYPE Normalisation SYSTEM "normalisation.dtd">

<Normalisation>
	<RelationSchema name="LIEFER">
		<Column>LIEFERANT</Column>
		<Column>ADRESSE</Column>
		<Column>ARTIKEL</Column>
		<Column>ANBAUGEBIET</Column>
		<Column>QUALITÄT</Column>
	</RelationSchema>
	<FunctionalDependency>
		<FunctionallyDependentOn>LIEFERANT</FunctionallyDependentOn>
		<FunctionallyAffected>ADRESSE</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>LIEFERANT</FunctionallyDependentOn>
		<FunctionallyDependentOn>ARTIKEL</FunctionallyDependentOn>
		<FunctionallyAffected>ANBAUGEBIET</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>ANBAUGEBIET</FunctionallyDependentOn>
		<FunctionallyAffected>LIEFERANT</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>ANBAUGEBIET</FunctionallyDependentOn>
		<FunctionallyAffected>QUALITÄT</FunctionallyAffected>
	</FunctionalDependency>
</Normalisation>

=== timhoelsken/easygoingcalculatorwithoutnumbers/Normalisation/resources/PROF-STUD.xml
<?xml version="1.0"?>

<!DOCTYPE Normalisation SYSTEM "normalisation.dtd">

<Normalisation>
	<RelationSchema name="PROF-STUD">
		<Column>PROF-NR</Column>
		<Column>STUD-NR</Column>
		<Column>VORLESUNG</Column>
		<Column>SCRIPT</Column>
		<Column>ABSCHLUSS</Column>
	</RelationSchema>
	<FunctionalDependency>
		<FunctionallyDependentOn>PROF-NR</FunctionallyDependentOn>
		<FunctionallyDependentOn>STUD-NR</FunctionallyDependentOn>
		<FunctionallyAffected>VORLESUNG</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>VORLESUNG</FunctionallyDependentOn>
		<FunctionallyAffected>SCRIPT</FunctionallyAffected>
	</FunctionalDependency>
	<FunctionalDependency>
		<FunctionallyDependentOn>STUD-NR</FunctionallyDependentOn>
		<FunctionallyAffected>ABSCHLUSS</FunctionallyAffected>
	</FunctionalDependency>
</Normalisation>
